// ── CONDUIT MANAGED FILE ────────────────────────────────────────────
// file:        cli/src/internal/bootstrap.ts
// description: Self-healing bootstrap — ensures Claude Code can invoke
//              Conduit natively via a user-agnostic shim at
//              ~/.claude/bin/conduit, and keeps ~/.claude/CLAUDE.md in sync.
//              Runs once per machine per version; skips silently otherwise.
// owner:       BOTH
// update:      Manual when invocation path, shim format, or CLAUDE.md block changes.
// schema:      none
// last_update: 2026-06-10
// ─────────────────────────────────────────────────────────────────────

import { existsSync, readFileSync, writeFileSync, mkdirSync, chmodSync } from 'node:fs';
import { execFileSync, execSync } from 'node:child_process';
import { join, resolve } from 'node:path';
import { homedir } from 'node:os';

const MARKER = '## Conduit CLI';

function getConduitRoot(): string {
  // dist/cli/src/internal/bootstrap.js → repo root (4 levels up)
  return resolve(__dirname, '..', '..', '..', '..');
}

function getVersion(conduitRoot: string): string {
  try {
    const pkg = JSON.parse(readFileSync(join(conduitRoot, 'package.json'), 'utf-8'));
    return pkg.version || '0.3.0';
  } catch {
    return '0.3.0';
  }
}

// ── CLAUDE.md block ──────────────────────────────────────────────────

// Bump when the CLAUDE.md block content changes — forces re-write on existing installs
// v6: PowerShell-correct invocation guidance (D4 — the bare `~/.claude/bin/conduit`
//     form fails in PowerShell; plain `conduit` works once ~/.claude/bin is on PATH)
const BLOCK_VERSION = '6';
const VERSION_MARKER = '<!-- conduit-block-v';

function buildClaudeBlock(conduitRoot: string): string {
  const nodePath = conduitRoot.replace(/\\/g, '/');
  const version = getVersion(conduitRoot);
  return `
${MARKER}
${VERSION_MARKER}${BLOCK_VERSION} -->
- Conduit is the AI-native delivery orchestration system for all HM repos
- **Run any conduit command as plain \`conduit <command> [args]\`** — the installer puts \`~/.claude/bin\` on the user PATH so this works in every shell.
- If plain \`conduit\` does not resolve (PATH entry missing), invoke the shim per shell:
  - Bash / Git Bash: \`~/.claude/bin/conduit <command>\`
  - PowerShell / cmd: \`~/.claude/bin/conduit.cmd <command>\`  (the \`.cmd\` extension is REQUIRED — the extensionless file is the bash shim and opens a flash-window in PowerShell)
  The shims are auto-generated by bootstrap and work for any user. Override the target by setting \`CONDUIT_NODE_ENTRY\`. Run \`conduit doctor\` to diagnose shim/PATH issues.
- Direct-path fallback (only if the shims are missing): \`node "${nodePath}/dist/cli/src/index.js" <command>\`
- Build: \`npm --prefix "${nodePath}" run build\` (npm resolved from PATH — works on Windows and macOS)
- Every repo with a CONDUIT.md is part of the Conduit network — read it before starting work

### CWD Rule — CRITICAL
Conduit is **cwd-sensitive**. It looks for CONDUIT.md and convoys/ relative to the current working directory.
- **Always run conduit commands from the repo the user is working in** (the repo that has CONDUIT.md)
- Example: \`cd "<target-repo-path>" && conduit context\`
- For conduit's OWN convoys (building Conduit itself), run from \`${nodePath}\`
- NEVER run conduit from a parent directory like \`Sandbox/\` — it will find nothing

### Entering Conduit Mode
When a user says "open Conduit", "start Conduit", or asks about convoys/gates/status:

1. **Show the Conduit banner** in your response FIRST:
\`\`\`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   CONDUIT — AI-native software delivery orchestration
   v${version}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
\`\`\`
2. Run \`conduit context\` to load the operating picture (from the current repo directory)
3. Read the repo's CONDUIT.md and CLAUDE.md for directives
4. If a convoy is active, show the convoy banner and enter Convoy Mode
5. If no convoy is active, show Standard Mode and offer next actions:
   - \`conduit convoy new\` — start a new delivery convoy
   - \`conduit status\` — check repo status
   - \`conduit init --scan\` — onboard a new repo
6. Stay in Conduit mode for the rest of the session — prefix key outputs with \`[CONDUIT]\`, \`[CONVOY]\`, \`[GATE]\` etc.
7. When in Convoy Mode, follow ALL rules in the repo's CLAUDE.md (gate protocol, checkpoint rules, directive loading)
`;
}

export function ensureClaudeMd(): void {
  try {
    const claudeDir = join(homedir(), '.claude');
    const claudeMdPath = join(claudeDir, 'CLAUDE.md');
    const conduitRoot = getConduitRoot();

    // Already bootstrapped?
    if (existsSync(claudeMdPath)) {
      const content = readFileSync(claudeMdPath, 'utf-8');
      if (content.includes(MARKER)) {
        const hasCurrentVersion = content.includes(`${VERSION_MARKER}${BLOCK_VERSION}`);
        const hasCorrectPath = content.includes(conduitRoot.replace(/\\/g, '/'));
        if (hasCurrentVersion && hasCorrectPath) {
          return; // All good — version and path match
        }
        // Outdated version or path changed — replace the block
        const before = content.substring(0, content.indexOf(MARKER));
        const afterMarker = content.indexOf('\n## ', content.indexOf(MARKER) + MARKER.length);
        const after = afterMarker >= 0 ? content.substring(afterMarker) : '';
        writeFileSync(claudeMdPath, before.trimEnd() + '\n' + buildClaudeBlock(conduitRoot).trimEnd() + '\n' + after, 'utf-8');
        return;
      }
      // Marker not found — append
      writeFileSync(claudeMdPath, content.trimEnd() + '\n' + buildClaudeBlock(conduitRoot), 'utf-8');
      return;
    }

    // No CLAUDE.md at all — create it
    if (!existsSync(claudeDir)) {
      mkdirSync(claudeDir, { recursive: true });
    }
    writeFileSync(claudeMdPath, `# Global User Settings\n${buildClaudeBlock(conduitRoot)}`, 'utf-8');
  } catch {
    // Bootstrap is best-effort — never block CLI operation
  }
}

// ── Conduit shim (~/.claude/bin/conduit) ─────────────────────────────

// Bump when the shim contents change — forces re-write on existing installs
// v2: conduit.cmd emits CRLF (D6 — cmd.exe mis-tokenizes LF-only batch files,
//     printing "'M' is not recognized" on every invocation)
export const SHIM_VERSION = '2';
export const SHIM_MARKER = 'conduit-shim-v';

/** Health probe for an on-disk conduit.cmd — used by `conduit doctor` (AC-5).
 *  crlfOnly: cmd.exe requires CRLF; any bare LF reintroduces D6.
 *  currentVersion: stale marker means bootstrap hasn't rewritten it yet. */
export function analyzeShimCmd(content: string): { crlfOnly: boolean; currentVersion: boolean } {
  return {
    crlfOnly: !/(^|[^\r])\n/.test(content),
    currentVersion: content.includes(`${SHIM_MARKER}${SHIM_VERSION}`),
  };
}

export function buildShimShell(conduitRoot: string): string {
  const nodePath = conduitRoot.replace(/\\/g, '/') + '/dist/cli/src/index.js';
  return `#!/usr/bin/env bash
# ${SHIM_MARKER}${SHIM_VERSION} — auto-generated by conduit bootstrap. Do not edit.
# Launches the Conduit CLI from this machine's install. Override target with
# CONDUIT_NODE_ENTRY to point at a different dist/cli/src/index.js.
exec node "\${CONDUIT_NODE_ENTRY:-${nodePath}}" "$@"
`;
}

export function buildShimCmd(conduitRoot: string): string {
  const nodePath = conduitRoot.replace(/\//g, '\\') + '\\dist\\cli\\src\\index.js';
  // cmd.exe requires CRLF — LF-only batch files mis-tokenize (D6: re-parses
  // mid-REM and emits "'M' is not recognized" on every invocation).
  return [
    '@echo off',
    `REM ${SHIM_MARKER}${SHIM_VERSION} — auto-generated by conduit bootstrap. Do not edit.`,
    "REM Launches the Conduit CLI from this machine's install. Override target with",
    'REM CONDUIT_NODE_ENTRY to point at a different dist\\cli\\src\\index.js.',
    'IF DEFINED CONDUIT_NODE_ENTRY (',
    '  node "%CONDUIT_NODE_ENTRY%" %*',
    ') ELSE (',
    `  node "${nodePath}" %*`,
    ')',
    '',
  ].join('\r\n');
}

function isCurrentShim(content: string, conduitRoot: string): boolean {
  if (!content.includes(`${SHIM_MARKER}${SHIM_VERSION}`)) return false;
  // Path must match — handles repos being moved between installs. (PORT-4:
  // a generic-marker fallback used to live here, which meant a moved checkout
  // never re-wrote the shim. The path check must be authoritative.)
  const posix = conduitRoot.replace(/\\/g, '/');
  const winUNC = conduitRoot.replace(/\//g, '\\');
  return content.includes(posix) || content.includes(winUNC);
}

// ── Daily auto-update (staying current) ──────────────────────────────
//
// dist/ is gitignored, so a `git pull` alone never updates the CLI a dev
// actually runs. This best-effort hook runs on every CLI invocation but is
// rate-limited to once per day via a timestamp file in ~/.conduit. It:
//   1. attempts a fast-forward-only pull of the central conduit checkout
//   2. rebuilds dist/ only when the pull actually moved HEAD
// Silent on any failure (offline, dirty tree, diverged, build error) — it
// must never block or slow normal CLI operation beyond the once-a-day check.
// Opt out with CONDUIT_AUTO_PULL=0.

const AUTO_PULL_INTERVAL_MS = 24 * 60 * 60 * 1000;

export function ensureDailyAutoUpdate(): void {
  try {
    if (process.env.CONDUIT_AUTO_PULL === '0') return;

    const stateDir = join(homedir(), '.conduit');
    const stampPath = join(stateDir, 'auto-pull-stamp');
    const now = Date.now();
    if (existsSync(stampPath)) {
      const last = parseInt(readFileSync(stampPath, 'utf-8').trim(), 10);
      if (Number.isFinite(last) && now - last < AUTO_PULL_INTERVAL_MS) return;
    }
    if (!existsSync(stateDir)) mkdirSync(stateDir, { recursive: true });
    // Stamp BEFORE attempting the pull so a failing remote doesn't retry on
    // every invocation for the rest of the day.
    writeFileSync(stampPath, String(now), 'utf-8');

    const root = getConduitRoot();
    if (!existsSync(join(root, '.git'))) return;

    const git = process.env.GIT_PATH || 'git';
    const rev = (): string =>
      execFileSync(git, ['-C', root, 'rev-parse', 'HEAD'], { stdio: 'pipe', timeout: 10000 })
        .toString().trim();

    const before = rev();
    execFileSync(git, ['-C', root, 'pull', '--ff-only', '--quiet'], { stdio: 'pipe', timeout: 30000 });
    const after = rev();
    if (before === after) return; // already current — nothing to rebuild

    // Source moved — rebuild so the NEXT invocation runs the new version.
    // execSync uses the platform shell, so `npm` resolves from PATH on both
    // Windows (npm.cmd) and POSIX without hardcoded install paths.
    execSync('npm run build', { cwd: root, stdio: 'pipe', timeout: 180000 });
    console.error(`CONDUIT: auto-updated central checkout (${before.slice(0, 7)} → ${after.slice(0, 7)}) and rebuilt CLI.`);
  } catch {
    // Best-effort — offline, diverged history, or build failure must never
    // block CLI operation. The next day's attempt will try again.
  }
}

export function ensureConduitShim(): void {
  try {
    const binDir = join(homedir(), '.claude', 'bin');
    const conduitRoot = getConduitRoot();

    if (!existsSync(binDir)) {
      mkdirSync(binDir, { recursive: true });
    }

    const shellPath = join(binDir, 'conduit');
    const cmdPath = join(binDir, 'conduit.cmd');

    // Shell shim
    const shellContent = buildShimShell(conduitRoot);
    let writeShell = true;
    if (existsSync(shellPath)) {
      const existing = readFileSync(shellPath, 'utf-8');
      if (isCurrentShim(existing, conduitRoot)) writeShell = false;
    }
    if (writeShell) {
      writeFileSync(shellPath, shellContent, 'utf-8');
      try {
        // Best-effort executable bit — ignored on NTFS, honored on POSIX.
        chmodSync(shellPath, 0o755);
      } catch {
        // chmod is not critical on Windows — Git Bash honors shebangs regardless.
      }
    }

    // Windows batch shim (for cmd.exe / PowerShell users; Claude Code Bash tool
    // uses the shell shim via Git Bash)
    const cmdContent = buildShimCmd(conduitRoot);
    let writeCmd = true;
    if (existsSync(cmdPath)) {
      const existing = readFileSync(cmdPath, 'utf-8');
      if (isCurrentShim(existing, conduitRoot)) writeCmd = false;
    }
    if (writeCmd) {
      writeFileSync(cmdPath, cmdContent, 'utf-8');
    }

    // Staying current: cheap, rate-limited fast-forward pull + rebuild.
    // Invoked from here because bootstrap is the one hook that runs on every
    // CLI invocation regardless of command (index.ts wiring is owned elsewhere).
    ensureDailyAutoUpdate();
  } catch {
    // Bootstrap is best-effort — never block CLI operation
  }
}
